### PR TITLE
Add `inner` keyword

### PR DESCRIPTION
**Pull request by qhy040404**
Support `inner` keyword.

A nested class marked as inner can access the members of its outer class. Inner classes carry a reference to an object of an outer class:
```kotlin
class Outer {
    private val bar: Int = 1
    inner class Inner {
        fun foo() = bar
    }
}

val demo = Outer().Inner().foo() // == 1
```

### CODE REVIEW

**Comment by nishtahir** [comment]
This change looks good however it's missing tests around the scopes. Would you mind adding tests for it? This is the file that would need to be updated https://github.com/nishtahir/language-kotlin/blob/master/test/Keywords.test.kt. You can update the corpus in the snapshot folder to include the keyword then run `npm run snapshot` to generate and inspect the scopes

**Comment by qhy040404** [comment]
I don't know whether it's ok. 
@nishtahir review request

**Comment by nishtahir** [comment]
Looks great. I made a small change to the regression test syntax.
Thank you for your contribution :tada:

**Comment by qhy040404** [comment]
Thanks! 😄

**Pull request merged**
